export const defaultGraph = [
  {
    url: "http://hekatestation.net/",
    depth: 0,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/rojo/rojo.html",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/one/one.html",
      "http://hekatestation.net/skulls.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/rojo/rojo.html",
    depth: 1,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/index.html",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/22020/22020.html",
      "http://hekatestation.net/files/bound.zip",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/bound.zip",
    depth: 2,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/one/one.html",
    depth: 1,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/2_18/2_18.html",
      "http://hekatestation.net/zaqqum/zaqqum.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zaqqum.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/zaqqum/zfiles/Twosret.zip",
      "http://hekatestation.net/zaqqum/zfiles/BERA.zip",
      "http://hekatestation.net/zaqqum/zfiles/Shirley.zip",
      "http://hekatestation.net/zaqqum/zfiles/TheSaturnSpread.zip",
      "http://hekatestation.net/zaqqum/zfiles/Eaten.zip",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/17_a.html",
    depth: 1,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/gruber/gruber.html",
      "http://hekatestation.net/files/BoF.pdf",
      "http://hekatestation.net/files/HSMM.zip",
      "http://hekatestation.net/index.html",
      "http://hekatestation.net/files/NTCNtC.pdf",
      "http://hekatestation.net/files/sulla.zip",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zfiles/TheSaturnSpread.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/22020/22020.html",
    depth: 2,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/index.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/rojo/rojo.html",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/one/one.html",
      "http://hekatestation.net/skulls.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/skulls.html",
    depth: 1,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/die.html",
    depth: 1,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/hekatestation.html",
      "http://hekatestation.net/rojo/rojo.html",
      "http://hekatestation.net/Isa_59_5.html",
      "http://hekatestation.net/maps.html",
      "http://hekatestation.net/GRID.html",
      "http://hekatestation.net/five.html",
      "http://hekatestation.net/719/719.html",
      "http://hekatestation.net/blank.html",
      "http://hekatestation.net/skulls.html",
      "http://hekatestation.net/Dir_G.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zfiles/Shirley.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/BoF.pdf",
    depth: 2,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zfiles/BERA.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zfiles/Eaten.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/Isa_59_5.html",
    depth: 2,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/five.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/three.html",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/two/two.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/2_18/2_18.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/2_18/texts/sleepaftertoyle.pdf",
      "http://hekatestation.net/2_18/texts/LetUsReturn.pdf",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/sulla.zip",
    depth: 2,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/two/two.html",
    depth: 3,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/three.html",
      "http://hekatestation.net/st_Nihemos.html",
      "http://hekatestation.net/animales/animales.html",
      "http://hekatestation.net/hekatestation.html",
      "http://hekatestation.net/Isa_59_5.html",
      "http://hekatestation.net/rojo/rojo.html",
      "http://hekatestation.net/five.html",
      "http://hekatestation.net/Dir_G.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/NTCNtC.pdf",
    depth: 2,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/gruber/gruber.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/files/Gruber_part2.zip",
      "http://hekatestation.net/files/Gruber_part3.zip",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/zaqqum/zfiles/Twosret.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/three.html",
    depth: 3,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/./files/StarsAboveRatsBelow.pdf",
      "http://hekatestation.net/lndex.html",
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/./files/LASTINLASTOUT.pdf",
      "http://hekatestation.net/17_a.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/HSMM.zip",
    depth: 2,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/hekatestation.html",
    depth: 2,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/Gruber_part3.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/blank.html",
    depth: 2,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/719/719.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/./TreasuresOfDarkness.pdf",
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/./palabracuartro.zip",
      "http://hekatestation.net/index.html",
      "http://hekatestation.net/./ThereIsLifeUnderground.pdf",
      "http://hekatestation.net/./BatShit.pdf",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/one/one.html",
    ],
    external: ["http://", "http://obsidiansnow.net/"],
    status: 200,
  },
  {
    url: "http://hekatestation.net/2_18/texts/LetUsReturn.pdf",
    depth: 3,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/st_Nihemos.html",
    depth: 4,
    content_type: "text/html",
    internal: ["http://hekatestation.net/Dir_G.html"],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/./files/StarsAboveRatsBelow.pdf",
    depth: 4,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/2_18/texts/sleepaftertoyle.pdf",
    depth: 3,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/Dir_G.html",
    depth: 2,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/smyrna.html",
      "http://hekatestation.net/files/Doeg.pdf",
      "http://hekatestation.net/files/ScienceAsPracticedInTheAbyss.pdf",
      "http://hekatestation.net/files/Book_13.pdf",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/maps.html",
    depth: 2,
    content_type: "text/html",
    internal: ["http://hekatestation.net/ffend.html"],
    external: ["http://obsidiansnow.net/"],
    status: 200,
  },
  {
    url: "http://hekatestation.net/./ThereIsLifeUnderground.pdf",
    depth: 3,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/files/Gruber_part2.zip",
    depth: 3,
    content_type: "application/x-zip-compressed",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/GRID.html",
    depth: 2,
    content_type: "text/html",
    internal: ["http://hekatestation.net/#"],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/smyrna.html",
    depth: 3,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/ffend.html",
    depth: 3,
    content_type: "text/html",
    internal: ["http://hekatestation.net/image/two.png"],
    external: ["http://www.obsidiansnow.net"],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/Book_13.pdf",
    depth: 3,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/./palabracuartro.zip",
    depth: 3,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/./files/LASTINLASTOUT.pdf",
    depth: 4,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/animales/animales.html",
    depth: 4,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/festival_of_ghosts.pdf",
      "http://hekatestation.net/thirteen_coffins.zip",
      "http://hekatestation.net/Daze.pdf",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/thirteen_coffins.zip",
    depth: 5,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/files/ScienceAsPracticedInTheAbyss.pdf",
    depth: 3,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/./BatShit.pdf",
    depth: 3,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/Daze.pdf",
    depth: 5,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/festival_of_ghosts.pdf",
    depth: 5,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/image/two.png",
    depth: 4,
    content_type: "image/png",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/files/Doeg.pdf",
    depth: 3,
    content_type: "application/pdf",
    internal: [],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/./TreasuresOfDarkness.pdf",
    depth: 3,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
  {
    url: "http://hekatestation.net/#",
    depth: 3,
    content_type: "text/html",
    internal: [
      "http://hekatestation.net/die.html",
      "http://hekatestation.net/rojo/rojo.html",
      "http://hekatestation.net/17_a.html",
      "http://hekatestation.net/one/one.html",
      "http://hekatestation.net/skulls.html",
    ],
    external: [],
    status: 200,
  },
  {
    url: "http://hekatestation.net/lndex.html",
    depth: 4,
    content_type: "text/html",
    internal: [],
    external: [],
    status: 404,
  },
];
